export { default as Stake } from "./Stake";
export { default as Dashboard } from "./Dashboard";
export { default as NotFound } from "./404";
export { default as Farms } from "./Farms";
export { default as SafeFarms } from './SafeFarms';
export { default as Swap } from './Swap';
export { RedirectToSwap } from './Swap/redirects';
export { default as Pools } from './Earn';
export { default as Ifos } from './Ifos';
export { default as Referral } from './Referral';